# Use the official Python image as a base image
FROM python:3.8-slim

# Set the working directory inside the container
WORKDIR /app/imageOne/chatbotApp

# Copy the chatbot app files into the container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir flask

# Expose the port your app runs on
EXPOSE 5001

# Command to run the Flask app
CMD ["python", "app.py"]
